// components/RootLayout.tsx
import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Views/Navbar";
import Wrapper from "@/components/Views/Wrapper";
import Footer from "@/components/Views/Footer";
import { ClerkProvider } from '@clerk/nextjs'

const playfairdisplay_inter = Playfair_Display({ subsets: ["latin"], variable: '--font-playfairdisplay' });

export const metadata: Metadata = {
  title: "The MOLEN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={playfairdisplay_inter.variable}>
          <Navbar />
          <Wrapper>
            {children}
          </Wrapper>
          <Footer />
        </body>
      </ClerkProvider>
    </html>
  );
}
